"""
gen_tests.py — generate tests from skills.md + spec.
Stages output in .generated/<feature>_tests/ — never touches tests/ directly.
Usage: python ai-tools/scripts/gen_tests.py --spec ai-tools/specs/spec_<name>.md
 
Context strategy:
  - spec '## Context files' section  → existing files the LLM needs as background
  - spec '## Files to generate' section → source files already promoted to src/
    These are automatically added as context so the LLM reads the actual
    implementation before writing tests for it.
"""
import re
import argparse
from pathlib import Path
from glob import glob
from datetime import datetime
from openai import OpenAI
 
AI_TOOLS     = Path(__file__).parent.parent
REPO_ROOT    = AI_TOOLS.parent
SKILLS       = (AI_TOOLS / "skills.md").read_text()
TEMPLATE     = (AI_TOOLS / "prompts/generate_tests.md").read_text()
STAGING_ROOT = REPO_ROOT / ".generated"
 
client = OpenAI()
 
# ── spec parsing ───────────────────────────────────────────────────────
 
def parse_context_from_spec(spec_text: str) -> list[str]:
    """Extract paths from '## Context files' section."""
    match = re.search(r"##\s+Context files\s*\n(.*?)(?=\n##|\Z)", spec_text, re.DOTALL)
    if not match:
        return []
    return [
        l.strip() for l in match.group(1).splitlines()
        if l.strip() and not l.strip().startswith("#")
    ]
 
def parse_generated_files_from_spec(spec_text: str) -> list[str]:
    """
    Extract paths from '## Files to generate' section.
    These are the source files already promoted to src/ after the code
    generation run. gen_tests.py uses them as context so the LLM reads
    the actual implementation before writing tests for it.
    This avoids needing to duplicate file paths in the spec's context section.
    """
    match = re.search(r"##\s+Files to generate\s*\n(.*?)(?=\n##|\Z)", spec_text, re.DOTALL)
    if not match:
        return []
    return [
        l.strip() for l in match.group(1).splitlines()
        if l.strip() and not l.strip().startswith("#")
    ]
 
def resolve_paths(patterns: list[str]) -> list[Path]:
    """Expand globs, deduplicate, return Paths that exist on disk."""
    seen: set[Path] = set()
    result: list[Path] = []
    for pat in patterns:
        for m in sorted(glob(pat, recursive=True) or [pat]):
            p = Path(m)
            if p.is_file() and p not in seen:
                seen.add(p)
                result.append(p)
    return result
 
# ── context block ──────────────────────────────────────────────────────
 
def build_context_block(paths: list[Path]) -> str:
    """Wrap each file in a labelled header so the LLM knows the source."""
    if not paths:
        return "None provided."
    return "\n\n".join(
        f"# --- FILE: {p} ---\n{p.read_text().strip()}" for p in paths
    )
 
# ── prompt ─────────────────────────────────────────────────────────────
 
def build_prompt(task: str, spec: str, context_block: str) -> str:
    return (
        TEMPLATE
        .replace("{{ skills_md }}", SKILLS)
        .replace("{{ spec }}",      spec)
        .replace("{{ task }}",      task)
        .replace("{{ context }}",   context_block)
    )
 
# ── output cleaning ────────────────────────────────────────────────────
 
def strip_markdown_fences(code: str) -> str:
    """
    Remove markdown code fences from LLM output.
    The LLM sometimes wraps code in ```python ... ``` even when told not to.
    This strips those fences so the written files contain only raw Python.
    """
    # remove opening fence: ```python or ``` at start of a line
    code = re.sub(r"^```(?:python)?\s*\n", "", code, flags=re.MULTILINE)
    # remove closing fence: ``` at start of a line
    code = re.sub(r"^```\s*$", "", code, flags=re.MULTILINE)
    return code.strip()
 
# ── output ─────────────────────────────────────────────────────────────
 
def write_manifest(staging: Path, spec_path: str, written: list[Path]) -> None:
    lines = [
        "# Generated manifest",
        f"spec: {spec_path}",
        f"generated: {datetime.now().isoformat()}",
        "status: pending",
        "",
        "## Files",
    ] + [str(f) for f in written]
    (staging / "manifest.md").write_text("\n".join(lines) + "\n")
 
# ── main ───────────────────────────────────────────────────────────────
 
def generate(spec_path: str, task: str) -> None:
    spec_text = Path(spec_path).read_text()
 
    # Load context files declared in the spec (background files)
    context_paths = resolve_paths(parse_context_from_spec(spec_text))
 
    # Load the source files that were generated by gen_code.py.
    # These now exist in src/ and are the primary context for test generation —
    # the LLM must read the actual implementation to write accurate tests.
    source_paths = resolve_paths(parse_generated_files_from_spec(spec_text))
 
    # Merge both lists, deduplicated, preserving order
    seen: set[Path] = set()
    all_paths: list[Path] = []
    for p in context_paths + source_paths:
        if p not in seen:
            seen.add(p)
            all_paths.append(p)
 
    # Report which files were found and which are missing
    if source_paths:
        print(f"  → source context: {len(source_paths)} file(s) from '## Files to generate'")
        for p in source_paths:
            print(f"      {p}")
    else:
        print("  → source context: none found — run gen_code.py and promote first")
 
    missing = [
        p for p in parse_generated_files_from_spec(spec_text)
        if not Path(p).is_file()
    ]
    if missing:
        print(f"  ⚠ {len(missing)} source file(s) not found on disk (not yet promoted?):")
        for m in missing:
            print(f"      {m}")
 
    context_block = build_context_block(all_paths)
 
    # Stage output
    spec_name = Path(spec_path).stem.replace("spec_", "")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    staging   = STAGING_ROOT / f"{spec_name}_tests" / timestamp
    staging.mkdir(parents=True, exist_ok=True)
 
    prompt = build_prompt(task, spec_text, context_block)
    print(f"  → prompt size: {len(prompt):,} chars")
 
    resp = client.chat.completions.create(
        model="gpt-4o",
        temperature=0.2,
        messages=[{"role": "user", "content": prompt}],
    )
 
    raw    = resp.choices[0].message.content
    blocks = re.split(r"#\s*===\s*FILE:\s*(.+?)\s*===", raw)
    pairs  = list(zip(blocks[1::2], blocks[2::2]))
 
    if not pairs:
        print("  ⚠ no FILE markers found — writing raw.txt to staging")
        (staging / "raw.txt").write_text(raw)
        return
 
    written: list[Path] = []
    for rel, code in pairs:
        # strip any markdown fences the LLM wrapped the code in
        clean_code = strip_markdown_fences(code)
        dest = staging / rel.strip()
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(clean_code + "\n")
        print(f"  staged  → {dest}")
        written.append(Path(rel.strip()))
 
    write_manifest(staging, spec_path, written)
    print(f"\n  ✓ review, then: python ai-tools/scripts/promote.py --staging {staging}")
 
 
if __name__ == "__main__":
    p = argparse.ArgumentParser(
        description="Generate tests from skills.md + spec (source files auto-loaded as context)"
    )
    p.add_argument("--spec", required=True, help="Path to spec file")
    p.add_argument(
        "--task",
        default="Generate tests for every acceptance criterion in <Spec>.",
        help="Optional: supplement the test generation task"
    )
    args = p.parse_args()
    generate(args.spec, args.task)